### ISSUE TITLE
Error calling Clippy

### ISSUE THREAD

**Issue by RobertMeh** [AtomLinter/linter-rust#100]
I wanted to use linter-rust 0.7.2 with clippy 0.0.114 on Windows 10. But got an error.

It tried to call:
`rustup run nightly cargo clippy -j 2 --manifest-path D:\project\Cargo.toml --message-format json`
which returns:
`error: Could not obtain cargo metadata.`

I belief the parameter:
`--manifest-path D:\project\Cargo.toml` is wrong there should be a `=` like this
`--manifest-path=D:\project\Cargo.toml`

**Comment by White-Oak** [comment]
Wow, that's strange. I'll check it out!

**Comment by aljelly** [comment]
This was fixed with #116.
