### ISSUE TITLE
linter-rust causing total breakage

### ISSUE THREAD

**Issue by HitomiTenshi** [AtomLinter/linter-rust#11]
Enabling linter-rust causes language-rust to crash, making atom hang until it notices said hanging and shows the Close / Keep Waiting message.

Additionally it causes autocomplete-plus and racer to stop working.

In order to get them working again I have to
- disable all community packages
- restart atom
- enable them again (except linter-rust)
- restart atom again

after that autocomplete-plus, racer and language-rust are working again, no hanging or anything.

I have linter installed.
Atom version: 0.199.0
OS: Windows 8.1 Pro 64 bit

**Comment by renkun-ken** [comment]
Exactly the same problem here with Atom 0.198.
