### ISSUE TITLE
Prevents file from being opened / Atom freeze

### ISSUE THREAD

**Issue by rugk** [AtomLinter/linter-rust#126]
STR:
1. Install Atom and everything https://areweideyet.com/ suggest you for Rust development.
2. Create a single file with [this example code](https://rustbyexample.com/hello/print.html).
3.  Try to open the file.

## What happens

Atom freezes.

## What should happen

It should at least not freeze.

Atom v1.23.3
Windows 10

**Comment by Arcanemagus** [comment]
Currently at least this site is recommending a list of 9 packages, are you sure that it is (was?) `linter-rust` that was causing your issue? Do you see the same thing if you disable `linter-rust`?

**Comment by rugk** [comment]
This issue is half a year old. Sorry, but I am not sure about anything regarding this issue. Cannot help here anymore, feel free to close.

But according to my bug description, I would say that I opened a Rust file and then it frooze, and otherwise it did not. Otherwise this bug report would be silly (and yeah, kinda less detailed, I have to admit.) But this is pure guessing, so yeah…

**Comment by Arcanemagus** [comment]
Since all it says is that you installed the entire list of packages, and due to the age I'll just assume that it's something either not related to this package, and has since been fixed in whatever caused it. 🤷‍♂️
