### ISSUE TITLE
Support for Windows Subsystem for Linux

### ISSUE THREAD

**Issue by ashthespy** [AtomLinter/linter-rust#138]
Would it be possible to support WSL?
I tried pointing to the relevant binaries with `bash -lc rustc` and `bash -lc cargo` but run into errors:
Running either of the above commands from my default shell seems to work fine.
```
[Linter] Error running Rust Error: '"bash -lc rustc"' is not recognized as an internal or external command,
operable program or batch file.
 ```

**Comment by gmist** [comment]
Maybe [wsl-proxy](https://github.com/watzon/wsl-proxy) can help:

rustc.bat
``` shell
@echo off
bash.exe -c "rustc %*"
```
