### ISSUE TITLE
It doesn't show errors in linter panel when there are, just some warning 

### ISSUE THREAD

**Issue by cata0309** [AtomLinter/linter-rust#145]
![image](https://user-images.githubusercontent.com/35623921/51610671-fa979580-1f25-11e9-96ec-5bd11e61bd5d.png)
What is color never ?? It redirects the error to the console and not to the linter package

**Comment by Arcanemagus** [comment]
What version of `rustc` are you using? That's an argument that (used to?) cause it to ignore any configuration that would output colorized output to make it parseable.

**Comment by cata0309** [comment]
I use the latest version of rustc
![image](https://user-images.githubusercontent.com/35623921/51626879-3728b880-1f49-11e9-8408-3d79ba1a189c.png)

**Comment by cata0309** [comment]
Any ideas ?
