### ISSUE TITLE
Spawning rustc process on every save

### ISSUE THREAD

**Issue by azerupi** [AtomLinter/linter-rust#16]
It seems like this plug-in is spawning a new rustc process on every save (or modification?) often causing multiple instances of it to run in parallel.

At some point I had 13 different rustc instances running in the background effectively saturating my processor for 5 minutes, making everything unusable.

**Comment by nixpulvis** [comment]
This is the only reason I cant use this package despite wanting to. The multiple compiler issue also seems to cause unexpected errors in my actual runs of cargo.

**Comment by colin-kiegel** [comment]
@nixpulvis I have got this _workaround_ https://gist.github.com/colin-kiegel/40432d62c70c2ddf7354 for linux. Its been of great help to me for months now. 

Btw. according to some upstream-bug-tickets I've been monitoring, it looks like cargo will finally get concurrency protection in one of the next releases. But if you happen to be on linux too, my workaround might help you too - until then. :-)

**Comment by nixpulvis** [comment]
@colin-kiegel Yea it's too bad concurrent support isn't in yet. Thanks for the script I might try adapting it for OS X.

**Comment by colin-kiegel** [comment]
@nixpulvis If the changes are minor, I will be happy to include it in my gist. :-)

PS: The concurrency fix has been merged in cargo just 2 days ago. https://github.com/rust-lang/cargo/pull/2486

**Comment by azerupi** [comment]
This one can be closed as well I think
