### ISSUE TITLE
Unresolved imports

### ISSUE THREAD

**Issue by fenhl** [AtomLinter/linter-rust#17]
As mentioned by @jgillich in #1, the linter fails to resolve imports that work fine in the actual `cargo build` command. I think this deserves its own issue, given that #1 is closed.

**Comment by b52** [comment]
@fenhl Could you provide a minimal example?

Else I would argue to close this issue, since it doesn't seem to be an issue. The linter already supports running `cargo build`, thus there shouldn't be such issue.

**Comment by fenhl** [comment]
It seems to be resolved by now.
