### ISSUE TITLE
Doesn't work at all on Windows

### ISSUE THREAD

**Issue by nixxquality** [AtomLinter/linter-rust#3]
rustc.exe is already in my %PATH%.

If left as the default value (empty), I get the following error:
```Uncaught Error: ENOENT, no such file or directory '<project directory>\rustc' fs.js:726```
If set to where Rust is installed, I get the following error:
```
Linter-Rust: "C:\Program Files (x86)\Rust\bin\rustc.exe" was not executable: "#1: stderr: 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
". Please, check executable path in the linter settings.
```
If set to where Rust is installed with wrapping quotes, I get the following error:
```Uncaught Error: ENOENT, no such file or directory '<project directory>\"C:\Program Files (x86)\Rust\bin\rustc.exe"' ```

Even if I go full workaround mode and set the executable path setting to ```../../../../PROGRA~2/Rust/bin/rustc.exe``` nothing seems to happen.

**Comment by BOOMER74** [comment]
Same error, set full path does not change anything.

**Comment by excaliburHisSheath** [comment]
I experience the `ENOENT` problem when using the default `rustc` value, but it goes away when I put in the full path. But even when I set the full path to rustc I still don't see any error messages or have any error output. As far as I can tell this is still broken on Windows.

**Comment by LaylConway** [comment]
I am having the same issue, other linter packages work fine.

**Comment by uadjet** [comment]
Necro? 
I'm having the exact same issue as excaliburHisSheath but on Linux.  If I change the path manually, it silently reports no errors. 

 rust -version: rustc 1.0.0-nightly (ea8b82e90 2015-03-17) (built 2015-03-18)

Seems to be mirrored here : https://github.com/AtomLinter/Linter/issues/330

**Comment by gmist** [comment]
@uadjet Please update ```linter-rust``` to the latest version.

**Comment by RyenNelsen** [comment]
Still does not work on Windows with version 0.0.6. Still getting `ENOENT` error.

**Atom Version**: 0.187.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory 'C:\Users\Ryen\AppData\Local\atom\app-0.187.0\rustc'

```
At fs.js:807

Error: ENOENT, no such file or directory 'C:\Users\Ryen\AppData\Local\atom\app-0.187.0\rustc'
  at Error (native)
  at fs.statSync (fs.js:807:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at LinterRust.Linter._cachedStatSync (C:\Users\Ryen\.atom\packages\linter\lib\linter.coffee:69:17)
  at LinterRust.Linter.getCmdAndArgs (C:\Users\Ryen\.atom\packages\linter\lib\linter.coffee:86:16)
  at LinterRust.Linter.lintFile (C:\Users\Ryen\.atom\packages\linter\lib\linter.coffee:127:24)
  at LinterRust.lintFile (C:\Users\Ryen\.atom\packages\linter-rust\lib\linter-rust.coffee:42:7)
  at LinterRust.lintFile (C:\Users\Ryen\.atom\packages\linter-rust\lib\linter-rust.coffee:1:1)
  at C:\Users\Ryen\.atom\packages\linter\lib\linter-view.coffee:158:18
  at Array.forEach (native)
  at C:\Users\Ryen\.atom\packages\linter\lib\linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
     -0:04.6 core:save (atom-text-editor.editor.is-focused)
```

It does however work if I use the absolute path to `rustc`. On my system, it is `C:\rust\bin\rustc.exe`. Rust is in my `Path` though, so it should work without having to change over to an absolute path.

**Comment by excaliburHisSheath** [comment]
I can confirm that with the latest updates it's now working on my machine, though I still need to enter the full path the the executable.

**Comment by LaylConway** [comment]
For me it now works as well, but only if I do not give the executable path and let it use the one at %PATH%.
