### ISSUE TITLE
Use Cargo instead of rustc

### ISSUE THREAD

**Issue by DominikGuzei** [AtomLinter/linter-rust#4]
Hey there!
Thanks for the awesome package, unfortunately it is not very useful yet because most rust projects are built using the Cargo package manager which handles dependencies etc.

Since this package uses `rustc` you get errors for any external crates, which makes it impractical for any real-world projects :-(

For inspiration you can take a look at the SublimeText 3 package that integrates with Cargo:
[SublimeLinter-contrib-rustc](https://github.com/oschwald/SublimeLinter-contrib-rustc)

**Comment by LaylConway** [comment]
One more merged, one more to go

**Comment by k2b6s9j** [comment]
Closed at the request of @b52.
