### ISSUE TITLE
Failed to run cargo

### ISSUE THREAD

**Issue by nathansizemore** [AtomLinter/linter-rust#41]
OS X v10.11.1
Atom v1.2.1

I received the following error on every save 

```
Failed to run cargo
spawn cargo ENOENT
```

**Comment by HarryLovesCode** [comment]
Temporary work around appears to be running with `atom --dev`, but ultimately, that's not fixing the issue.

**Comment by abrkn** [comment]
Having same issue. `--dev` workaround solves it

**Comment by jmquigs** [comment]
It looks like this occurs if cargo isn't in your path and you haven't set an override path in the settings.  Could probably make it look around for cargo in the usual places (/usr/bin, /usr/local/bin).

**Comment by HarryLovesCode** [comment]
@jmquigs Cargo is definitely in my path, but I haven't tried overriding it yet.

**Comment by kbknapp** [comment]
Using [multirust](https://github.com/Diggsey/multirust-rs) and having `cargo` and `rustc` in your `PATH` still causes this issue. But adding `$HOME/.multirust/bin/{cargo,rustc}` to the override solved it :)

**Comment by ConnorGBrewster** [comment]
I also have multirust and it is causing this same issue. Running Atom in dev mode does fix the issue.

**Comment by Sinkler** [comment]
try to write the full path to cargo in settings of linter-rust. it fixed this problem for me. sample: https://monosnap.com/file/zIhqa8oMDHuwujw7mlKAwDWk47QhyH

**Comment by ConnorGBrewster** [comment]
@Sinkler that seemed to fix the issue! I was trying to set it to the cargo located in `~/.multirust/toolchains/stable/bin/cargo`, which did not work but setting it to `/usr/local/bin/cargo` worked.

**Comment by Sinkler** [comment]
@ConnorGBrewster i don't have multirust, but i think that atom settings don't support relative paths. try to enter `/Users/USERNAME/.multirust/toolchains/stable/bin/cargo`

**Comment by Arcanemagus** [comment]
You are correct that there is no automatic expansion of shell shortcuts like `~`, you need to enter the _full_ path if you are using a custom location and not relying on `$PATH`.

**Comment by chriskrycho** [comment]
Trying this with the new rustup tool (which installs things to `~/.cargo/bin` by default), and regardless of how I set the paths (full, partial, etc.) it always results in `spawn /Users/chris/.cargo/bin/cargo ENOENT`.

**Comment by chriskrycho** [comment]
I haven't been able to track it down *all* the way, but it's something in [the creation of the `BufferedProcess`](https://github.com/AtomLinter/linter-rust/blob/48cbcc9c34afe061549bf84daa1cb7401a54920d/lib/linter-rust.coffee#L44). Here is the `options` argument passed to it:

```js
{
  command: '/Users/chris/.cargo/bin/cargo',
  args: ["check", "-j", 4, "--manifest-path", "/Users/chris/dev/p/rust/rope/Cargo.toml"],
  options: <the options built up>,
  stdout: <your custom stdout handler>,
  stdin: <your custom stdin handler>,
  exit: <your custom exit handler>
}
```

I can also attach the *options* as necessary (later).

Running `new BufferedProcess({ command })` fails itself; there may be something upstream? I've run Node's own `child_process.spawn()` with this exact same command path and args with no issues.

**Comment by Arcanemagus** [comment]
@chriskrycho What version of Atom are you on? What OS?

**Comment by chriskrycho** [comment]
@Arcanemagus I'm running Atom 1.7.3, on OS X. The actual issue I was having was that there was some whitespace in my `rustc` and `cargo` paths, because I used `which cargo | pbcopy` and `which rustc | pbcopy` to look them up, and that grabbed a newline in each case. Getting rid of that whitespace made the issue go away, and the PR I submitted (#58) resolved that issue more generally. :smile:

**Comment by Arcanemagus** [comment]
Ah, for some reason I had it in my head that that hadn't fully fixed it for you, instead of you just being unsure if it fixed it for others :wink:.

**Comment by chriskrycho** [comment]
Clarification appreciated!

**Comment by ChristopherRabotin** [comment]
Yo, can this be fixed?! I don't want to be bothered to run Atom with the `--dev` flag all the time. Kthxbye

**Comment by White-Oak** [comment]
Well, there was a comment today which was deleted by its author, not sure if this was about a problem.

I'm not sure if this issue is still present, since we have recoded the way arguments and environment is processed.

**Comment by ChristopherRabotin** [comment]
@White-Oak I had mistakenly reported that the issue was still present (and my comment was full of frustration about the issue, so sorry about that). Instead, I hadn't configured the cargo paths correctly in the plugin.

**Comment by White-Oak** [comment]
@ChristopherRabotin I'm glad that you figured your problem out!

**Comment by liquidnight2** [comment]
This still seems to occur, at leas on my desktop. I have  app-editors/atom-1.23.3 , a regular rust installation.  And the error depends on if I 
- start the Atom editor from the fluxbox menu, then it appears
- start it from console, then it does not appear.

After applying the solution from @Sinkler, the error does no more appear. 


Still, how can I open a bash  inside atom to output the PATH variable ?
