### ISSUE TITLE
Allow using multirust

### ISSUE THREAD

**Issue by flying-sheep** [AtomLinter/linter-rust#46]
I’d like to use `multirust run nightly cargo` as command instead of default cargo, in order to make clippy work

**Comment by Arcanemagus** [comment]
Does https://github.com/AtomLinter/linter-rust/pull/45 not work for you?

**Comment by flying-sheep** [comment]
it works if `cargo` is the nightly version.

i want to use `multirust run nightly cargo ...`

**Comment by colin-kiegel** [comment]
The question is, whether that is a good default for everyone. I think *it is* for as long as clippy depends in nightly. Of course this adds a new dependency to use multirust in this setting, but I think its pretty widespread among people using nightly, so it should be OK.

@flying-sheep: you could take a look at #45 and just change the mapping of clippy -> cargo clippy in A New pull request

**Comment by flying-sheep** [comment]
maybe it would be good to add a selection box:

> multirust toolchain:
> * disabled (use plain `cargo`/`rustc`)
> * stable
> * nightly
> * beta

if possible, that setting would be disabled if multirust isn’t detected at startup/opening of settings pane

**Comment by colin-kiegel** [comment]
That could work, too. The question is, *are there other use cases to lint with a different toolchain than the multirust override for the project?* - except for clippy. Do you think there are more use cases?

**Comment by flying-sheep** [comment]
good question. probably not.

indeed in my [cargo-clippy](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cargo-clippy-git) AUR package, i used an approach that’s simply: “use `multirust run nightly cargo` if available, else fallback to `cargo`”.

**Comment by colin-kiegel** [comment]
Yes, I think this behaviour would be the most reasonable choice right now.

**Comment by White-Oak** [comment]
I suppose, adding a checkbox `use multirust nightly to lint` similar to `use Cargo if possible` would be acceptable. However, using Clippy is the only usecase for this.

**Comment by flying-sheep** [comment]
i thought we decided to simply use multirust if available with clippy and don’t use it if it isn’t and for anything else.

**Comment by White-Oak** [comment]
@flying-sheep yeah, that's more reasonable.

**Comment by mninja** [comment]
Unfortunately Atom now will display `Failed to run multirust: spawn multirust ENOENT` every single time if multirust isn't installed. It would make more sense to use an option instead of that autodetect, or perhaps detect in a way that doesn't pop up an error.

**Comment by mninja** [comment]
I've pushed #53 as a possible solution.
