### ISSUE TITLE
Disable certain types of warnings

### ISSUE THREAD

**Issue by jaysonsantos** [AtomLinter/linter-rust#54]
Some times is hard to read the code because of unused code when you are prototyping, would it be possible to hide some warnings?
![screenshot from 2016-03-30 09-08-27](https://cloud.githubusercontent.com/assets/51510/14134360/05c6a66c-f657-11e5-8e9f-592aa925bfa4.png)

**Comment by White-Oak** [comment]
@jaysonsantos how about `#[allow(dead_code)]` and `#![allow(dead_code)`?

**Comment by jaysonsantos** [comment]
@White-Oak Those are good to check on the build, but on the linting is kinda troublesome

**Comment by White-Oak** [comment]
@jaysonsantos so do you want a certain setting like "Don't show warnings"?

**Comment by jaysonsantos** [comment]
Not all warning, just some like dead code

**Comment by colin-kiegel** [comment]
@jaysonsantos: I believe rust itself offers enough flexibility here:

When you are prototyping, you can add a crate level allow (in your main crate), notice the !:
* `#![allow(dead_code)]` - always allow dead_code
* `#![cfg_attr(test, allow(dead_code))]` - allow dead_code for test builds only

You can also use this for only one `mod foo` or only a single `struct` (without the ! then).

**Comment by White-Oak** [comment]
@colin-kiegel yes, that was advised before (like two comments before)

**Comment by White-Oak** [comment]
@jaysonsantos, I can add such a setting via PR, not sure if it will be accepted, since it is really specific.

**Comment by colin-kiegel** [comment]
@White-Oak: I know - I was emphasizing the flexibility and mentioning the cfg_attr-macro which you didn't mention before.

I would definitely vote against such a specific option which is redundant with rusts built-in functionality.

**Comment by White-Oak** [comment]
@colin-kiegel definetily agree with you. On a second guess - you can simply disable rust-linter when prototyping.

**Comment by White-Oak** [comment]
@colin-kiegel though, it is really specific, would most use that?

**Comment by colin-kiegel** [comment]
@White-Oak: Not yet, I'd guess. But I believe something like this could be a good workflow in a case like this.

Now that I really understood @jaysonsantos desired workflow, I am not that much against it anymore... I guess it _could_ make sense to suppress stuff in linter, although being a bit redundant. But IMO this should be customizable then. The question is: Would it work for all rust-linting "backends"?

**Comment by White-Oak** [comment]
@colin-kiegel what I have in mind is a field in linter's settings with values of desired to be ignored lintings (dead_code, unused_result etc). If those are found in warning text, it is removed from list of shown warnings.

**Comment by White-Oak** [comment]
And yes, it would work for all backends, since all of them output with the same format!

**Comment by colin-kiegel** [comment]
Sounds reasonable to me
