### ISSUE TITLE
options.PATH ignored by BufferedProcess

### ISSUE THREAD

**Issue by saghm** [AtomLinter/linter-rust#59]
I've been experiencing a bug after upgrading to version 0.4.6 where I'm not getting any error messages from Cargo. After delving into the code and eventually (accidentally) realizing that the issue disappears when Atom is run directly from the command line, I tracked down the issue to [this](https://github.com/AtomLinter/linter-rust/blob/master/lib/linter-rust.coffee#L22). While making a copy rather than modifying global state definitely seems like a better idea, it seems to be preventing Cargo from being properly run for me because `BufferedProcess` actually uses the global state—it doesn't even look at `options.PATH`! The documentation [here](https://github.com/atom/atom/blob/master/src/buffered-process.coffee#L26-L78) indicates that the options it uses don't include the path, and in the function definition it calls [`getCmdPath`](https://github.com/atom/atom/blob/master/src/buffered-process.coffee#L176-L182), which looks directly at `process.env`. I'm not sure when this change occurred in Atom (I looked back a few commits on the file without seeing anything about the path), but it appears that `BufferedProcess` has been ignoring the custom path for a while, and using custom paths only worked before due to the fluke of modifying the global state.

Given that this bug will only occur in very specific setups (i.e. not running Atom from the command line and having `cargo`/`rustc` installed in non-standard path locations) and that the issue seems to be more with the `BufferedReader` and not with the package (forcing people to modify global state just seems like bad practice), I can understand if you'd prefer not to change it back to modifying the global state. However, I figured it would still be worth reporting the issue just so you'd be aware that the custom path was being ignored (and due to the off chance that someone else ends up having the same issue as me and wants to know what causes it).

**Comment by dikaiosune** [comment]
I'm running into an issue that seems very much like this after switching from multirust to rustup.rs.

**Comment by saghm** [comment]
That's exactly when I first had the issue. The best "solution" I came up with was just to symlink `rustc` and `cargo` (and any `cargo-*` utilities I had installed with `cargo install`) into `/usr/local/bin`, which was one of the paths in the default sets that Atom was using.

Since then, I've switched to using the `rustup` package in the AUR (which installs the binaries into `/usr/bin`), but that won't work for anyone not using Arch Linux (and still may not be preferable for people who don't want to have to wait for the maintainer to update the package, installing rustup into a custom directory prevents `rustup self update` from working).

**Comment by White-Oak** [comment]
@saghm, I wonder if you are still there, and can test whether this bug is still present on the latest linter (0.5.6). There was a change in the way env variables are passed, maybe its got this issue resolved.

**Comment by Arcanemagus** [comment]
It might be a good idea to bring in the `atom-linter` library that most of the other linters use, or just pull in the `sb-exec` `npm` module directly here if you don't want to bring that in fully.

There are _tons_ of improvements and edge case fixes in there from the experiences getting all the other linters to run properly.

**Comment by saghm** [comment]
@White-Oak Sorry for the delay in responding, but I'm still here! I'll take a look sometime this weekend to see if it's fixed
