### ISSUE TITLE
Specify features

### ISSUE THREAD

**Issue by W4RH4WK** [AtomLinter/linter-rust#60]
Apparently `clippy` does no longer set the `clippy` feature flag automatically due to some incompatibilities. I'd like to request an entry in the options menu which lets me specify features passed to the cargo command (space or comma separated list would suffice).

#30 may be related to this.

**Comment by White-Oak** [comment]
Yes, gets really hard to lint, when writing code for non-default targets, but specifying features is certainly possible, I'll make a PR for it.

**Comment by W4RH4WK** [comment]
I'd lint the non-default targets manually on the commandline. Thanks for your incoming PR.

**Comment by White-Oak** [comment]
Saying `non-default targets` I really meant `non-default features`, sorry for misunderstandment.
