### ISSUE TITLE
Support for new JSON format in nightly currently unsupported

### ISSUE THREAD

**Issue by gregvirgin** [AtomLinter/linter-rust#75]
On OS X, rust-linter does not work with anything newer than nightly-2016-08-09-x86_64-apple-darwin and rust-linter version 0.4.6. Updating either the toolchain or linter-rust and it simply stops linting.

I'm happy to run this down but I do not see how to get debugging logs to understand what is happening. Please advise.

**Comment by gregvirgin** [comment]
Not the issue does not seem to be [this](https://github.com/AtomLinter/linter-rust/issues/59), as none of the workarounds helped.

**Comment by White-Oak** [comment]
Try to run Atom in a dev mode. To do this either:
* run atom from command line `atom --dev <path>`
* in opened Atom look for View -> Developer -> Open in Dev Mode

linter-rust will now report about everything rustc outputted to stderr, if there is somethinf suspicious, post it here please!

**Comment by gregvirgin** [comment]
0.4.6 is what I'm using (the last working version). So I'll just assume It's JSON support. I'll rename the issue to JSON support.

A little strange that new versions of rust-linter don't work with that old version of rust. I can test that if you want.

**Comment by White-Oak** [comment]
@gregvirgin ok, so linter-rust works this way:
* it checks an output of `rustc --version` to see if the version is more 'up-to-date' than `2016-08-08`
  * if yes, linter-rust enters 'JSON-errors-mode' to consume errors from rustc
  * if no, linter-rust stays in 'old-errors-mode' to consume errors as before to have backwards compatibility.

Considering this, can you please tests the outputs of:
* `rustc --version`
* `RUSTFLAGS='--error-format=json' cargo build` on your project

**Comment by gregvirgin** [comment]
Interesting development- everything is now working.

- rustc 1.13.0-nightly (a7b2232d2 2016-09-07)
- linter-rust 0.5.6

I think we can close this.

**Comment by White-Oak** [comment]
Oh well :)
Feel free to reopen this, if issues are encountered again.
