### ISSUE TITLE
Switching between terminal and Atom with linter-rust causes a clean rebuild

### ISSUE THREAD

**Issue by White-Oak** [AtomLinter/linter-rust#77]
This causes long rebuilds of a full project.
However, if I remain in one environment (say `linter-rust`) clean rebuilds do not happen.

This was introduced recently, probably, with my change of how environment is passed to `cargo`. 

I will debug this and try to fix, but I'm curious if I'm the only one who encountered this.
Please upvote this or leave a response if you have experienced such an issue.

**Comment by White-Oak** [comment]
Okay, so the issue is because `RUSTFLAGS` differ when calling from linter-rust and terminal.
linter-rust (to get JSON errors) adds `--error-format=json` to the env variable `RUSTFLAGS`, but the terminal environment doesn't have it, so cargo forces clean recompile, which is kind of sad.

The current workaround is to add `--error-format=json` to `RUSTFLAGS` (before anything if it's not empty). The downside of this is getting no "new errors" (tbh I don't like them very much and can't make a regexp for them) in terminal.

I'll think what can be done about this.

**Comment by colin-kiegel** [comment]
is this reported upstream?

**Comment by White-Oak** [comment]
@colin-kiegel I'm pretty sure it's not. If you don't mind I'll report it a bit later.

**Comment by White-Oak** [comment]
Blocked by this: https://github.com/rust-lang/cargo/issues/2982

**Comment by White-Oak** [comment]
The blocking PR was merged, so it soon wiil hit nightly, and I'll add a check to fix this bug at least on nightly

**Comment by White-Oak** [comment]
This has been landed in 0.7.0 version of `linter-rust` just fyi.

**Comment by Razican** [comment]
Is this working on stable? Cargo [added](https://blog.rust-lang.org/2016/11/10/Rust-1.13.html#cargo-features) `--message-format` in stable in 1.13, but I don't seem to be using it correctly: linting in Atom and running `cargo build` on terminal makes it to compile again.

Is it because `linter-rust` uses RUSTFLAGS instead of `cargo --message-format`?

**Comment by White-Oak** [comment]
@Razican well, something went a bit unexpected, and `--message-format` was released ahead of time. See https://github.com/rust-lang/cargo/issues/3282

**Comment by White-Oak** [comment]
Well, looks like it was supposed to! I'll add a couple of checks to ensure it works on stable
