### ISSUE TITLE
Linting is broken since new error message format in rust 1.12

### ISSUE THREAD

**Issue by GeorgeKT** [AtomLinter/linter-rust#78]
Title says it all. The plugins just says no errors, and when you actually build it in a terminal, you see all the errors.

Tried several of the cargo command options, but none of them result in errors shown.

**Comment by jviide** [comment]
Noticed the same thing and opened pull request #79 as a suggested fix.

The version check for JSON error support accepted only version strings for nightly builds. The new patched version also accepts non-nightlies with version number >= 1.12.0.
